### ISSUE TITLE
Unable to build on Ubuntu 19.04

### ISSUE THREAD

**Issue by adamdossa** [hicommonwealth/edgeware-node#111]
I get the below build error. I've tried the below toolchains:
stable-x86_64-unknown-linux-gnu
nightly-2019-06-30-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

Any advice appreciated!

```
error[E0432]: unresolved import `hashbrown`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmi-validation-0.1.0/src/lib.rs:31:5
   |
31 | use hashbrown::HashSet;
   |     ^^^^^^^^^ use of undeclared type or module `hashbrown`

error: aborting due to previous error

```

**Comment by raykyri** [comment]
Hi Adam,

I think this is fixed on the latest `master`. Let us know if you still have any issues.
